# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: |
#     cd .github/workflows
#     cat uipath-cicd.yml
#   displayName: 'Run a one-line script'

trigger:
- main   # Equivalente a on: push en main

pool:
  vmImage: 'windows-latest'  # Igual que GitHub Actions

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self

    - powershell: |
        $version = "1.0.$(Build.BuildId)"
        $outputDir = "output"

        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

        dotnet new tool-manifest
        dotnet tool install UiPath.CLI.Windows
        dotnet tool run uipcli package pack project.json -o $outputDir -v $version
      displayName: 'Pack Robot'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'output'
        ArtifactName: 'RobotCompilado'
        publishLocation: 'Container'


# 🔽 TU DEPLOY (equivalente a "needs: build")
- stage: Deploy
  dependsOn: Build   # 👈 equivalente a needs: build
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self

    # 👇 equivalente a download-artifact
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'RobotCompilado'
        downloadPath: '$(System.ArtifactsDirectory)'
    # - task: UiPathDeploy@2
    #   inputs:
    #     orchestratorConnection: '${{ variables.OrchestratorConnection }}'
    #     packagesPath: '$(System.DefaultWorkingDirectory)'
    #     folderName: '$(ServerDirectory)'
    #     traceLevel: 'None'
    - task: UiPathDeploy@6
      inputs:
        orchestratorConnection: 'uipath'
        packagesPath: '$(System.ArtifactsDirectory)'
        folderName: 'Shared'