# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: |
#     cd .github/workflows
#     cat uipath-cicd.yml
#   displayName: 'Run a one-line script'

trigger:
- main   # Equivalente a on: push en main

pool:
  vmImage: 'windows-latest'  # Igual que GitHub Actions

steps:
- checkout: self

# Simulación de ejecución (logs)
- script: |
    echo "Iniciando Robot..."
    echo "Hola Mundo desde Azure DevOps"
    echo "Ajuste"
  displayName: 'Ejecutar Robot (Simulación de Log)'

# Empaquetado con UiPath CLI
- powershell: |
    $version = "1.0.$(Build.BuildId).$(Rev:.r)"
    $outputDir = "output"

    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

    Write-Host "1. Preparando el manifiesto de herramientas .NET..."
    dotnet new tool-manifest

    Write-Host "2. Instalando UiPath CLI oficial..."
    dotnet tool install UiPath.CLI.Windows

    Write-Host "3. Empaquetando el proyecto..."
    dotnet tool run uipcli package pack project.json -o $outputDir -v $version

    Write-Host "¡Empaquetado listo!"
    Get-ChildItem -Path $outputDir
  displayName: 'Pack Robot (UiPath CLI)'

# Publicar artefacto
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output'
    ArtifactName: 'RobotCompilado'
    publishLocation: 'Container'


